### ISSUE TITLE
Certificate issue recovery cert

### ISSUE THREAD

**Issue by sensationunddesign** [floysh/DCC-green-pass-decoder#9]
@floysh will there be an update for recovery certificates because of the shortening of validity? The validity was 6 months now three…thx a lot

**Comment by floysh** [comment]
Not likely as there's no logic for checking the certificate's validity atm. There is only a check on the digital signature to determine if the certificate is authentic, but there are other criteria to be met in order for the certificate to be considered valid. I never intended this project as a substitute for the official verification tools, partly because I have neither time nor desire to track the regulatory developments of all EU countries (depending on the legislation, the validity of a certificate may vary from one country to another).
